name: tracking_web
description: "OCWC Tracking is the mobile application developed by the Ministry of Labour and Vocational Training of the Kingdom of Cambodia for Cambodian migrant workers to track and monitor his/her document and application process status for working overseas. Only users who registered with OCWC Tracking are eligible to track and monitor the application status through scanning QR Code on his/her OCWC card or by entering his/her personal detail such as name and date of birth."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  http: ^1.2.2
  dio: ^5.5.0+1
  intl: ^0.19.0
  get: ^4.6.6
  rflutter_alert: ^2.0.7
  quickalert: ^1.1.0
  auto_size_text: ^3.0.0
  mask_text_input_formatter: ^2.9.0
  google_fonts: ^6.2.1
  easy_stepper: ^0.8.3
  flutter_localization: ^0.2.0
  get_storage: ^2.1.1
  flip_card: ^0.7.0
  qr_code_scanner: ^1.0.1
  camera: ^0.10.5+9
  image_picker_for_web: ^3.0.3
  mobile_scanner: ^5.1.0
  file_picker: ^8.0.0+1
  url_strategy: ^0.2.0
  scanning_effect: ^1.0.4
  cupertino_icons: ^1.0.6
  dropdown_search: ^5.0.6
  cloudflare_turnstile: ^0.2.1
  cached_network_image: ^3.3.1
  qr_code_vision: ^0.1.2
  pdf_render: ^1.4.10
  flutter_cache_manager: ^3.3.2
  url_launcher: ^6.3.0
  html: ^0.15.4
  web: ^0.5.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: SourceSansPro-Regular
      fonts:
        - asset: assets/fonts/SourceSansPro-Regular.otf

    - family: SourceSansPro-Bold
      fonts:
        - asset: assets/fonts/SourceSansPro-Bold.otf

    - family: Battambang
      fonts:
        - asset: assets/fonts/KhmerOSBattambang-Regular.ttf

    - family: Battambang-Bold
      fonts:
        - asset: assets/fonts/Battambang-Bold.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
