import 'package:get/get.dart';

class Message extends Translations {
  @override
  Map<String, Map<String, String>> get keys {
    return {
      "en_US": {
        "title": "Find Your OCWC information",
        "subTitle": "Enter latin name and date of birth",
        "track": "Track",
        "latin": "Latin Name",
        "date": "Date Of Birth",
        "nameWarning": "Latin name is required.",
        "dateWarning": "Date of birth is required.",
        "dateMatch": "Date of birth is invalid.",
        "workerDetail": "Worker Detail",
        "gender": "Gender",
        "ocwcNo": "OCWC No",
        "khmername": "Khmer Name",
        "latinname": "Latin Name",
        "country": "Country",
        "SenderAgency": "Sender Agency",
        "trackInfo": "OCWC Information",
        "workAddress": "Address work",
        "appbarTitle": "OCWC Tracking",
        "loading": "Loding...",
        "finding": "Finding Data",
        "try": "Try Again",
        "workerpro": "Worker Profile",
        "dateofbirth": "your Date of Birth",
        'workers': "All Workers",
        "cardDate": "Expiration Card",
        "noData": "No Data",
        "issuseDate": "Date of Issuse",
        "expireDate": "Date of Expiry",
        "image": "Image",
        "okay": "Okay",
        "close": "Close",
        "viewcard": "View Card"
      },
      "km_KH": {
        "title": "ស្វែងរកព័ត៌មាន OCWC",
        "subTitle": "សូមបញ្ចូលឈ្មោះឡាតាំងនិងថ្ងៃខែឆ្នាំកំណើត",
        "track": "ត្រួតពិនិត្យ",
        "latin": "ឈ្មោះឡាតាំង",
        "date": "ថ្ងៃខែឆ្នាំកំណើត",
        "nameWarning": "ឈ្មោះឡាតាំង តម្រូវអោយបញ្ចូល។",
        "dateWarning": "ថ្ងៃ.ខែ.ឆ្នាំ.កំណើត តម្រូវអោយបញ្ចូល។",
        "dateMatch": "ថ្ងៃ.ខែ.ឆ្នាំ.កំណើត មិនត្រឹមត្រូវ។",
        "workerDetail": "ព័ត៌មាន",
        "gender": "ភេទ",
        "ocwcNo": "លេខ OCWC",
        "khmername": "ឈ្មោះ",
        "latinname": "ឈ្មោះឡាតាំង",
        "country": "ប្រទេស",
        "SenderAgency": "ភ្នាក់ងារ",
        "trackInfo": "ព័ត៌មាន OCWC",
        "workAddress": "អសយដ្ឋានការងារ",
        "appbarTitle": "ប្រព័ន្ធតាមដាន OCWC",
        'loading': "សូមរង់ចាំ",
        "finding": "កំពុងស្វែងរក",
        "try": "ព្យាយាមម្តងទៀត",
        "workerpro": "ព័ត៌មានផ្ទាល់ខ្លួន",
        "dateofbirth": "ថ្ងៃខែឆ្នាំកំណើត",
        'workers': "ពលករទាំងអស់",
        "noData": "គ្នានទិន្នន័យ",
        "cardDate": "សុពលភាពបណ្ណ",
        "issuseDate": "កាលបរិច្ឆេទចេញបណ្ណ",
        "expireDate": "កាលបរិច្ឆេទអស់សុពលភាព",
        "image": "រូបភាព",
        "okay": "យល់ព្រម",
        "close": "បិទ",
        "viewcard": "មើលកាត"
      }
    };
  }
}
